"""usuarios y articulos

Revision ID: 4c0da0f6a5c9
Revises: 
Create Date: 2026-06-17 16:28:37.988985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0da0f6a5c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('lista_orden', sa.String(length=50), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('set_modelo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('matricula', sa.String(length=100), nullable=True),
    sa.Column('matricula_ii', sa.String(length=100), nullable=True),
    sa.Column('epoca', sa.String(length=50), nullable=True),
    sa.Column('caja', sa.String(length=100), nullable=True),
    sa.Column('unidades', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('ejes', sa.String(length=50), nullable=True),
    sa.Column('rodaje', sa.String(length=50), nullable=True),
    sa.Column('longitud', sa.String(length=50), nullable=True),
    sa.Column('administracion', sa.String(length=100), nullable=True),
    sa.Column('librea', sa.String(length=100), nullable=True),
    sa.Column('envejecido', sa.String(length=50), nullable=True),
    sa.Column('clasificacion', sa.String(length=100), nullable=True),
    sa.Column('mercancia', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('necesidades', sa.String(length=300), nullable=True),
    sa.Column('rodaje_detalle', sa.String(length=100), nullable=True),
    sa.Column('imagen', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articulos')
    # ### end Alembic commands ###
